name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build

      # Deploy ONLY the built files. Requires GitHub Secrets:
      # FTP_SERVER = ftp.abas.lv
      # FTP_USERNAME = your FTP user rooted at /home2/abaslv/public_html/hotelkandava.lv
      # FTP_PASSWORD = that user's password
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/              # must end with /
          server-dir: ./                # FTP home should be public_html/hotelkandava.lv
          dangerous-clean-slate: true   # wipe target before upload
          exclude: |
            .htaccess                   # keep SPA routing file on the server
